# vim:fileencoding=utf-8:foldmethod=marker

# BEGIN_KITTY_THEME
# Vague
include current-theme.conf
# END_KITTY_THEME

# BEGIN_KITTY_FONTS
font_family      family="ComicShannsMono Nerd Font Mono"
bold_font        auto
italic_font      auto
bold_italic_font auto
font_size 15
# END_KITTY_FONTS

map alt+w launch --cwd=current
map alt+enter launch --cwd=curren
map alt+q close_window

hide_window_decorations yes

background_opacity 0.8
dynamic_background_opacity yes

cursor none
cursor_trail 1
cursor_trail_decay 0.1 0.4
cursor_trail_start_threshold 0

map alt+j kitten pass_keys.py neighboring_window bottom alt+j
map alt+k kitten pass_keys.py neighboring_window top    alt+k
map alt+h kitten pass_keys.py neighboring_window left   alt+h
map alt+l kitten pass_keys.py neighboring_window right  alt+l

allow_remote_control yes
listen_on unix:/tmp/kitty

map alt+v launch --stdin-source=@screen_scrollback --type=overlay nvim --cmd "set eventignore=FileType" +"nnoremap q ZQ" +"call nvim_open_term(0, {})" +"set nomodified nolist" +"$" -
