# fr
[[mgr.prepend_keymap]]
on = ["f", "r"]
run = "plugin fr rg"
desc = "Search file by content (rg)"

[[mgr.prepend_keymap]]
on = ["f", "a"]
run = "plugin fr rga"
desc = "Search file by content (rga)"

# lazygit
[[mgr.prepend_keymap]]
on   = [ "g", "g" ]
run  = "plugin lazygit"
desc = "run lazygit"
